services:
  mysql:
    image: mysql:8.0
    container_name: rando-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rando_ouest
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - rando-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  react:
    build:
      context: ./randoreact
      dockerfile: Dockerfile.dev
    container_name: rando-react
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - ./randoreact:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - rando-network
  laravel:
    build: ./randolaravel
    container_name: rando-laravel
    restart: unless-stopped
    ports:
      - "8000:8000"  # Changez de 9000 à 8000
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=rando_ouest
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - rando-network

volumes:
  mysql_data:

networks:
  rando-network:
    driver: bridge


