version: '3.8'

services:
  laravel-docker:
    image: ghcr.io/nade0478/cda-api-prod:latest
    -10,12 +8,11 @@ services:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-docker.rule=Host(`api.srv807224.hstgr.cloud`)"
      - "traefik.http.routers.laravel-docker.rule=Host(`api.rando-ouest.com`)"
      - "traefik.http.routers.laravel-docker.entrypoints=websecure"
      - "traefik.http.routers.laravel-docker.tls.certresolver=myresolver"

    volumes:
      - ~/storage:/var/www/app/storage 
      - /root/storage:/var/www/app/storage/app/public 

  vue-docker:
    image: ghcr.io/nade0478/cda-spa-prod:latest
    -37,6 +34,8 @@ services:
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    volumes:
      - /root/datadir:/var/lib/mysql

  traefik:
    image: traefik:v3.2
    -46,12 +45,11 @@ services:
      - "--providers.docker.exposedbydefault=false" 
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=nade.projet.rando@gmail.com"
      - "--certificatesresolvers.myresolver.acme.email=support@rando-ouest.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"