services:
  laravel-api-docker:
    build: ./rando-ouest-laravel-NOUVELLE-BRANCHE-MAIN
    container_name: laravel-api-docker
    ports:
      - 8000:8000  # Laravel écoute sur 8000
    volumes:
      - ./rando-ouest-laravel-NOUVELLE-BRANCHE-MAIN:/var/www/html
      - storage:/var/www/html/storage
    depends_on:
      - mysql_db
    networks:
      - app-net
    restart: unless-stopped
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  react-docker:
    build: ./Projet-rando-front
    container_name: react-docker
    ports:
      - 3000:3000
    networks:
      - app-net
    restart: unless-stopped

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net
    restart: unless-stopped

volumes:
  storage:
  mysql_data:

networks:
  app-net:
