name: CI

on:
  push:
    branches:
      - "NOUVELLE-BRANCHE-MAIN"

jobs:
  docker:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v1

      - name: Installer Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Pause pour laisser Docker démarrer
        run: sleep 10s
        shell: bash

      - name: Lancer les conteneurs Docker
        run: |
          for i in {1..5}; do
            docker-compose up -d && break || sleep 15
          done

      - name: Installer les dépendances PHP (Composer)
        run: docker exec laravel-docker bash -c "composer install"

      - name: Migrer la base de données Laravel
        run: docker exec laravel-docker bash -c "php artisan migrate --force"

      - name: Peupler la base de données Laravel
        run: docker exec laravel-docker bash -c "php artisan db:seed --force"

      - name: Migrer la base de données de test Laravel
        run: docker exec laravel-docker bash -c "php artisan migrate --env=testing --force"

      - name: Installer les dépendances Node.js (frontend)
        run: docker exec ecoride-front bash -c "npm install"

      - name: Exécuter les tests Jest (frontend)
        run: docker exec ecoride-front bash -c "npm test"
